import { configureStore, createSlice } from '@reduxjs/toolkit';

// Define the initial state for the game stats
const initialState = {
  gamesPlayed: 0,
  wins: 0,
  losses: 0,
};

// Create a slice for game stats
const gameStatsSlice = createSlice({
  name: 'gameStats',
  initialState,
  reducers: {
    incrementGamesPlayed: (state) => {
      state.gamesPlayed++;
    },
    incrementWins: (state) => {
      state.wins++;
    },
    incrementLosses: (state) => {
      state.losses++;
    },
    resetGameStats: (state) => {
      state.gamesPlayed = 0;
      state.wins = 0;
      state.losses = 0;
    },
  },
});

// Export actions generated by createSlice
export const {
  incrementGamesPlayed,
  incrementWins,
  incrementLosses,
  resetGameStats,
} = gameStatsSlice.actions;

// Export the selector to get the game stats from the state
export const selectGameStats = (state) => state.gameStats;

// Configure and export the store
export const store = configureStore({
  reducer: {
    gameStats: gameStatsSlice.reducer,
  },
});
